### ISSUE TITLE
CVUSA dataset

### ISSUE THREAD

**Issue by ahmednreldin** [PyBigStar/S3Geo#1]
Hello ,  

I’d like to have a download link to the CVUSA dataset used in this paper

 " Sixing Hu, Mengdan Feng, Rang M. H. Nguyen, Gim Hee Lee. CVM-Net: Cross-View Matching Network for Image-Based Ground-to-Aerial Geo-Localization. In IEEE Conference on Computer Vision and Pattern Recognition (CVPR), June 2018." 

I’m trying to reproduce and test the deep learning model in the repository corresponding to this paper (david-husx/crossview_localisation (github.com)), but I can’t use the current one due to missing “splits” directory, 
I tried googling for the dataset, I found this website Crossview USA (CVUSA) (uky.edu), but there are multiple dead links, specifically the subset used for localization evaluation.

 If it is possible could you tell us How to test the pretrained models?

**Comment by PyBigStar** [comment]
Sorry, I can't provide you with the dataset directly. I can only suggest that you go to the repo of the CVUSA to ask for a valid download link.
